(ns genmlx.perfbench-curvefit
  "Performance benchmark: polynomial regression (curvefit).

   Matches GenJAX perfbench suite:
   - Same model: y = a + b·x + c·x² with a,b,c ~ Normal(0,1), σ=0.05
   - Same dataset: 50 points, seed 42 (hardcoded from JAX PRNG output)
   - Same timing methodology: double-nested loop (min per inner, mean±std of outer)
   - Compatible JSON output for combine_results.py

   IS:  vectorized-importance-sampling (shape-based batching, single model execution)
   HMC: compiled HMC with step-size 0.01, 20 leapfrog steps

   Output: genjax/examples/perfbench/data_cpu/curvefit/genmlx/*.json"
  (:require [genmlx.mlx :as mx]
            [genmlx.mlx.random :as rng]
            [genmlx.choicemap :as cm]
            [genmlx.dist :as dist]
            [genmlx.dynamic :as dyn]
            [genmlx.protocols :as p]
            [genmlx.inference.importance :as is]
            [genmlx.inference.mcmc :as mcmc])
  (:require-macros [genmlx.gen :refer [gen]]))

;; ---------------------------------------------------------------------------
;; Shared dataset (generated by JAX PRNG with seed=42, 50 points)
;; ---------------------------------------------------------------------------

(def true-a 0.5)
(def true-b -1.25)
(def true-c 2.0)
(def noise-std 0.05)
(def n-points 50)

(def xs-data
  (mapv #(/ % 49.0) (range 50)))

(def ys-data
  [0.4985847771167755  0.49867936968803406 0.4670966863632202
   0.43864354491233826 0.4050852954387665  0.4041197896003723
   0.30488234758377075 0.40003788471221924 0.37529996037483215
   0.38338857889175415 0.3089717626571655  0.37717026472091675
   0.3861168920993805  0.36318734288215637 0.30330780148506165
   0.3502485752105713  0.3329485356807709  0.31801244616508484
   0.23827843368053436 0.3542235195636749  0.3109130263328552
   0.2726636230945587  0.24499496817588806 0.3717282712459564
   0.3554992079734802  0.44361770153045654 0.330072283744812
   0.3917330205440521  0.452309250831604   0.5377517938613892
   0.5190575122833252  0.5044896602630615  0.5115360021591187
   0.599144458770752   0.6011276841163635  0.6101635098457336
   0.6839280128479004  0.7078725695610046  0.7055920958518982
   0.727923572063446   0.8016946911811829  0.8697319626808167
   0.8885982632637024  0.9479345679283142  1.0089064836502075
   0.9859774112701416  1.111462950706482   1.2016266584396362
   1.2164047956466675  1.2148115634918213])

;; ---------------------------------------------------------------------------
;; Model (matches GenJAX polynomial regression)
;; ---------------------------------------------------------------------------

(def curvefit-model
  (dyn/auto-key
    (gen [xs]
      (let [a (trace :a (dist/gaussian 0 1))
            b (trace :b (dist/gaussian 0 1))
            c (trace :c (dist/gaussian 0 1))]
        (doseq [[j x] (map-indexed vector xs)]
          (trace (keyword (str "y" j))
                 (dist/gaussian
                  (mx/add a (mx/add (mx/multiply b (mx/scalar x))
                                    (mx/multiply c (mx/scalar (* x x)))))
                  noise-std)))))))

;; ---------------------------------------------------------------------------
;; Observations choicemap
;; ---------------------------------------------------------------------------

(def observations
  (apply cm/choicemap
    (mapcat (fn [j y]
              [(keyword (str "y" j)) (mx/scalar y)])
            (range n-points) ys-data)))

;; ---------------------------------------------------------------------------
;; Timing utilities (matching GenJAX's timing_utils.py)
;; ---------------------------------------------------------------------------

(defn perf-now
  "High-resolution timer in seconds."
  []
  (/ (js/performance.now) 1000.0))

(defn timing
  "Double-nested timing loop. Returns {:times [float...] :mean float :std float}.
   times = min of inner-repeats per outer repeat (in seconds)."
  [f repeats inner-repeats]
  (let [times (loop [i 0 acc (transient [])]
                (if (>= i repeats)
                  (persistent! acc)
                  (let [inner-min
                        (loop [j 0 best js/Infinity]
                          (if (>= j inner-repeats)
                            best
                            (let [start (perf-now)
                                  _ (f)
                                  elapsed (- (perf-now) start)]
                              (recur (inc j) (min best elapsed)))))]
                    (recur (inc i) (conj! acc inner-min)))))
        n (count times)
        mean (/ (reduce + times) n)
        variance (/ (reduce + (map #(let [d (- % mean)] (* d d)) times)) n)
        std (js/Math.sqrt variance)]
    {:times times :mean mean :std std}))

(defn benchmark-with-warmup
  "Warmup runs + timing."
  [f {:keys [warmup-runs repeats inner-repeats]
      :or {warmup-runs 5 repeats 50 inner-repeats 50}}]
  (dotimes [_ warmup-runs] (f))
  (timing f repeats inner-repeats))

;; ---------------------------------------------------------------------------
;; JSON output
;; ---------------------------------------------------------------------------

(def fs (js/require "fs"))
(def path-mod (js/require "path"))

(def output-dir
  (.resolve path-mod (js/process.cwd)
            "genjax/examples/perfbench/data_cpu/curvefit/genmlx"))

(defn ensure-dir [dir]
  (when-not (.existsSync fs dir)
    (.mkdirSync fs dir #js {:recursive true})))

(defn write-json [filename data]
  (ensure-dir output-dir)
  (let [filepath (str output-dir "/" filename)]
    (.writeFileSync fs filepath (js/JSON.stringify (clj->js data) nil 2))
    (println (str "  Wrote: " filepath))))

;; ---------------------------------------------------------------------------
;; IS benchmark
;; ---------------------------------------------------------------------------

(defn run-is-benchmark [n-particles {:keys [repeats inner-repeats]
                                     :or {repeats 50 inner-repeats 50}}]
  (println (str "\n=== IS benchmark: " n-particles " particles ==="))
  (let [task-fn (fn []
                  (mx/tidy
                    #(let [r (is/vectorized-importance-sampling
                               {:samples n-particles}
                               curvefit-model [xs-data] observations)]
                       ;; Materialize to ensure computation completes (= block_until_ready)
                       (mx/materialize! (:log-ml-estimate r)
                                        (:weight (:vtrace r)))
                       nil)))
        {:keys [times mean std]} (benchmark-with-warmup task-fn
                                   {:warmup-runs 5
                                    :repeats repeats
                                    :inner-repeats inner-repeats})
        result {:framework "genmlx"
                :method "importance_sampling"
                :n_particles n-particles
                :n_points n-points
                :times (vec times)
                :mean_time mean
                :std_time std}]
    (println (str "  Mean: " (.toFixed (* mean 1000) 3) " ms  "
                  "Std: " (.toFixed (* std 1000) 3) " ms"))
    (write-json (str "is_n" n-particles ".json") result)
    result))

;; ---------------------------------------------------------------------------
;; HMC benchmark
;; ---------------------------------------------------------------------------

(defn run-hmc-benchmark [n-samples {:keys [repeats inner-repeats step-size
                                           leapfrog-steps burn]
                                    :or {repeats 50 inner-repeats 10
                                         step-size 0.01 leapfrog-steps 20
                                         burn 50}}]
  (println (str "\n=== HMC benchmark: " n-samples " samples ==="))
  (let [task-fn (fn []
                  (mx/tidy
                    #(let [samples (mcmc/hmc
                                     {:samples n-samples
                                      :step-size step-size
                                      :leapfrog-steps leapfrog-steps
                                      :burn burn
                                      :addresses [:a :b :c]
                                      :compile? true
                                      :device :cpu}
                                     curvefit-model [xs-data] observations)]
                       ;; Materialize final samples
                       (mx/eval! (first samples))
                       nil)))
        {:keys [times mean std]} (benchmark-with-warmup task-fn
                                   {:warmup-runs 5
                                    :repeats repeats
                                    :inner-repeats inner-repeats})
        result {:framework "genmlx"
                :method "hmc"
                :n_samples n-samples
                :n_warmup burn
                :n_points n-points
                :times (vec times)
                :mean_time mean
                :std_time std
                :step_size step-size
                :n_leapfrog leapfrog-steps}]
    (println (str "  Mean: " (.toFixed (* mean 1000) 3) " ms  "
                  "Std: " (.toFixed (* std 1000) 3) " ms"))
    (write-json (str "hmc_n" n-samples ".json") result)
    result))

;; ---------------------------------------------------------------------------
;; Verification: sanity-check model + data
;; ---------------------------------------------------------------------------

(defn verify-model []
  (println "\n=== Verification ===")
  (println (str "First 5 ys: " (vec (take 5 ys-data))))

  ;; Quick IS to check posterior
  (let [r (is/vectorized-importance-sampling
           {:samples 5000} curvefit-model [xs-data] observations)
        vtrace (:vtrace r)
        choices (:choices vtrace)
        weights (:weight vtrace)
        _ (mx/materialize! weights)
        ;; Softmax for weighted mean
        log-probs (mx/subtract weights (mx/logsumexp weights))
        probs (mx/exp log-probs)
        _ (mx/materialize! probs)
        a-samples (cm/-get-value (cm/-get-submap choices :a))
        b-samples (cm/-get-value (cm/-get-submap choices :b))
        c-samples (cm/-get-value (cm/-get-submap choices :c))
        wmean (fn [s] (mx/realize (mx/sum (mx/multiply s probs))))
        a-est (wmean a-samples)
        b-est (wmean b-samples)
        c-est (wmean c-samples)
        log-ml (mx/realize (:log-ml-estimate r))]
    (println (str "Log-ML estimate: " (.toFixed log-ml 2)))
    (println (str "Posterior means (weighted):"))
    (println (str "  a = " (.toFixed a-est 4) " (true: " true-a ")"))
    (println (str "  b = " (.toFixed b-est 4) " (true: " true-b ")"))
    (println (str "  c = " (.toFixed c-est 4) " (true: " true-c ")"))
    (when (or (js/isNaN log-ml) (== log-ml js/-Infinity))
      (println "WARNING: log-ML is not finite!"))))

;; ---------------------------------------------------------------------------
;; Main — run mode selection
;; ---------------------------------------------------------------------------
;;
;; QUICK mode (~10 min): IS only, reduced repeats. Good for development.
;; FULL mode (~7 hours): IS + all HMC. Run overnight.
;;
;; Usage:
;;   bun run --bun nbb test/genmlx/perfbench_curvefit.cljs              # quick
;;   BENCH=full bun run --bun nbb test/genmlx/perfbench_curvefit.cljs   # full
;;
;; Estimated times (M2 Mac):
;;   IS  1000/5000/10000 particles, 50×50 repeats:  ~7 min total
;;   HMC 100 samples,  10×3 repeats:                ~7 min
;;   HMC 500 samples,  10×3 repeats:                ~32 min
;;   HMC 1000 samples, 10×3 repeats:                ~64 min
;;   HMC 5000 samples,  3×2 repeats:                ~100 min
;;   HMC 10000 samples, 3×2 repeats:                ~200 min
;;
;; Note: HMC is slow because each mcmc/hmc call re-compiles the Metal
;; chain from scratch. JAX caches JIT across calls; MLX does not (yet).
;; The IS comparison is the compelling story — near-constant time across
;; 1K–10K particles thanks to shape-based batching on Metal GPU.

(defn run-quick []
  (println "Mode: QUICK (IS only, ~10 min)")

  (verify-model)

  ;; IS benchmarks — the flagship result
  (doseq [n [1000 5000 10000]]
    (run-is-benchmark n {}))

  ;; Single HMC point for reference (smallest chain)
  (run-hmc-benchmark 100 {:repeats 5 :inner-repeats 2}))

(defn run-full []
  (println "Mode: FULL (IS + HMC, ~7 hours — run overnight)")

  (verify-model)

  ;; IS benchmarks (fast — shape-based batching)
  (doseq [n [1000 5000 10000]]
    (run-is-benchmark n {}))

  ;; HMC benchmarks (each run re-compiles the full chain)
  (doseq [n [100 500 1000]]
    (run-hmc-benchmark n {:repeats 10 :inner-repeats 3}))
  (doseq [n [5000 10000]]
    (run-hmc-benchmark n {:repeats 3 :inner-repeats 2})))

(defn main []
  (println "GenMLX Perfbench: Polynomial Regression (Curvefit)")
  (println (str "Dataset: " n-points " points, noise σ=" noise-std))
  (println (str "Output: " output-dir))

  (let [mode (aget js/process.env "BENCH")]
    (if (= mode "full")
      (run-full)
      (run-quick)))

  (println "\n=== Done ===")
  ;; Exit before Bun tries to GC MLX native objects (causes SIGTRAP)
  (.exit js/process 0))

(main)
